<a href="https://colab.research.google.com/github/vaibhavkatex/The-Internship-2026/blob/main/Kaggle_Dataset_Analysis_%26_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from google.colab import files
Uploaded = files.upload()

Saving anime.csv to anime (1).csv

In [6]:
df = pd.read_csv("anime.csv")

In [7]:
df

,anime_id,title,score,rank,popularity,members,synopsis,start_date,end_date,type,episodes,image_url
0,28977,Gintama°,9.05,8,347,680037,"Gintoki, Shinpachi, and Kagura return as the f...",2015-01-01,2016-01-01,TV,51.0,https://cdn.myanimelist.net/images/anime/3/720...
1,57555,Chainsaw Man Movie: Reze-hen,9.18,2,962,282129,Sequel to Chainsaw Man .,2025-01-01,2025-01-01,Movie,1.0,https://cdn.myanimelist.net/images/anime/1763/...
2,11061,Hunter x Hunter (2011),9.03,9,8,3107455,Hunters devote themselves to accomplishing haz...,2011-01-01,2014-01-01,TV,148.0,https://cdn.myanimelist.net/images/anime/1337/...
3,52991,Sousou no Frieren,9.29,1,121,1269074,During their decade-long quest to defeat the D...,2023-01-01,2024-01-01,TV,28.0,https://cdn.myanimelist.net/images/anime/1015/...
4,9969,Gintama',9.02,11,406,601940,"After a one-year hiatus, Shinpachi Shimura ret...",2011-01-01,2012-01-01,TV,51.0,https://cdn.myanimelist.net/images/anime/4/503...
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1351,Angel Cop,6.05,9994,4755,26983,"Sometime in the future, terrorism in Japan has...",1989-01-01,1994-01-01,OVA,6.0,https://cdn.myanimelist.net/images/anime/1377/...
9996,33339,Zhongguo Jingqi Xiansheng,6.05,9991,10781,3192,A lost form of magic is revived from the Easte...,2014-01-01,2016-01-01,ONA,63.0,https://cdn.myanimelist.net/images/anime/1637/...
9997,2840,Youkoso Lodoss-tou e!,6.05,9988,11348,2710,This movie is the compilation of the 27 mini-p...,1998-01-01,1998-01-01,Movie,1.0,https://cdn.myanimelist.net/images/anime/7/613...
9998,33764,Ying Xiong Bie Nao,6.05,9987,17963,502,The series takes place on a parallel world fil...,2015-01-01,2015-01-01,ONA,13.0,https://cdn.myanimelist.net/images/anime/1013/...
9999,49700,Arifureta Shokugyou de Sekai Saikyou Picture D...,6.05,9996,10448,3510,An online motion graphic spin-off series that ...,2019-01-01,2019-01-01,ONA,13.0,https://cdn.myanimelist.net/images/anime/1169/...

In [10]:
df.head()

,anime_id,title,score,rank,popularity,members,synopsis,start_date,end_date,type,episodes,image_url
0,28977,Gintama°,9.05,8,347,680037,"Gintoki, Shinpachi, and Kagura return as the f...",2015-01-01,2016-01-01,TV,51.0,https://cdn.myanimelist.net/images/anime/3/720...
1,57555,Chainsaw Man Movie: Reze-hen,9.18,2,962,282129,Sequel to Chainsaw Man .,2025-01-01,2025-01-01,Movie,1.0,https://cdn.myanimelist.net/images/anime/1763/...
2,11061,Hunter x Hunter (2011),9.03,9,8,3107455,Hunters devote themselves to accomplishing haz...,2011-01-01,2014-01-01,TV,148.0,https://cdn.myanimelist.net/images/anime/1337/...
3,52991,Sousou no Frieren,9.29,1,121,1269074,During their decade-long quest to defeat the D...,2023-01-01,2024-01-01,TV,28.0,https://cdn.myanimelist.net/images/anime/1015/...
4,9969,Gintama',9.02,11,406,601940,"After a one-year hiatus, Shinpachi Shimura ret...",2011-01-01,2012-01-01,TV,51.0,https://cdn.myanimelist.net/images/anime/4/503...

In [11]:
df.shape

(10000, 12)

In [13]:
df.columns

Index(['anime_id', 'title', 'score', 'rank', 'popularity', 'members',
       'synopsis', 'start_date', 'end_date', 'type', 'episodes', 'image_url'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   anime_id    10000 non-null  int64
 1   title       10000 non-null  object
 2   score       10000 non-null  float64
 3   rank        10000 non-null  int64
 4   popularity  10000 non-null  int64
 5   members     10000 non-null  int64
 6   synopsis    9998 non-null   object
 7   start_date  9998 non-null   object
 8   end_date    9916 non-null   object
 9   type        10000 non-null  object
 10  episodes    9952 non-null   float64
 11  image_url   10000 non-null  object
dtypes: float64(2), int64(4), object(6)
memory usage: 937.6+ KB

In [15]:
df.isnull()

,anime_id,title,score,rank,popularity,members,synopsis,start_date,end_date,type,episodes,image_url
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
df.isnull().sum()

anime_id       0
title          0
score          0
rank           0
popularity     0
members        0
synopsis       2
start_date     2
end_date      84
type           0
episodes      48
image_url      0
dtype: int64

In [18]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [19]:
df.duplicated().sum()

np.int64(1)

In [21]:
df.describe()

,anime_id,score,rank,popularity,members,episodes
count,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,9952.000000
mean,24129.128000,6.980589,5000.494000,6490.903700,1.075309e+05,15.702271
std,19948.188153,0.619406,2886.898727,4646.309341,2.733514e+05,41.865696
min,1.000000,6.050000,1.000000,1.000000,2.260000e+02,1.000000
25%,4055.500000,6.470000,2500.750000,2591.750000,4.270250e+03,1.000000
50%,21406.000000,6.900000,5000.500000,5564.500000,1.817900e+04,11.000000
75%,40028.750000,7.390000,7500.250000,9824.250000,8.469275e+04,13.000000
max,62863.000000,9.290000,10000.000000,22184.000000,4.262220e+06,1787.000000

In [22]:
numerical = df.select_dtypes(include=['int64','float64']).columns

print(numerical)

Index(['anime_id', 'score', 'rank', 'popularity', 'members', 'episodes'], dtype='object')